### ISSUE TITLE
Feature Request: provide a list of already selected contacts to not appear

### ISSUE THREAD

**Issue by peterhav** [broakenmedia/MultiContactPicker#14]
This feature request is about providing a set of contact ID's to the builder. This set contains already selected contacts that should not be shown in the picker, or that should be 'unselectable'.

**Comment by broakenmedia** [comment]
Can you let me know a potential use case? Something like allowing the user to go back after selecting some already and adding more presumably?

**Comment by peterhav** [comment]
Yes, in my app the users selects contacts that should appear in the app. He can repeat this action as often as needed. 
In order to prevent duplicate contacts from appearing in the app, and to prevent confusion during selection, not showing the already selected contacts in the contact picker would be the cleanest solution.

**Comment by broakenmedia** [comment]
This has now been added and will be available in the next release (1.8). You can supply it with a list of String contact IDs or simply an ArrayList of ContactResult:

    .setSelectedContacts("87", "10", "3")

    .setSelectedContacts(new ArrayList<ContactResult>())

**Comment by broakenmedia** [comment]
1.8.3 now available! See readme
