### ISSUE TITLE
Shows Memory leaks

### ISSUE THREAD

**Issue by ramupal2613** [broakenmedia/MultiContactPicker#15]
attached screenshot for memory leaks.
![d57cd019-890a-431a-a6c6-142c47fda5ee](https://user-images.githubusercontent.com/29447349/37862264-05e48dd6-2f70-11e8-8d00-1e396da877ba.jpg)

**Comment by broakenmedia** [comment]
Can you expand the + symbols?

**Comment by broakenmedia** [comment]
It looks like it's not related to MCP itself. Rather io.okdone.chat holding onto a reference or something.

**Comment by ramupal2613** [comment]
it showing rxnewthreadscheduler 
![b33d204d-5118-4ee1-a2bd-5531d0a032a8](https://user-images.githubusercontent.com/29447349/38015266-e57c2e48-3288-11e8-9c2e-b6d2ec0c98a8.jpg)

**Comment by broakenmedia** [comment]
Not sure what to do here. Too vague for me to trace!

**Comment by ramupal2613** [comment]
i think call of RxContacts.fetch method need to dispose on activity destory.

**Comment by broakenmedia** [comment]
Should now be fixed in next release

**Comment by broakenmedia** [comment]
1.8.3 now available! See readme
