### ISSUE TITLE
Feature request : Allow only contacts with phone numbers, email or both.

### ISSUE THREAD

**Issue by ch4ndu** [broakenmedia/MultiContactPicker#19]
Also, Asynchronously loading the contacts is not letting us select them until all of them are loaded...and with 3000+ contacts in some lists, this is practically unusable for a good 5-10 seconds till the load is complete. Any plans to add a progress dialog/bar and prevent user interaction until the load is complete?

**Comment by broakenmedia** [comment]
This will be available in the next release. This should become available in the next day or so (1.8) You will now be able to stipulate:

.setLoadingType(MultiContactPicker.LOAD_SYNC) or .setLoadingType(MultiContactPicker.LOAD_ASYNC)

Async is the current default, SYNC will hide results and show loader until ALL results are loaded.

You will also be able to limit the results to contacts that contain an EMAIL, PHONE or BOTH:

.limitToColumn(LimitColumn.NONE/LimitColumn.EMAIL/LimitColumn.PHONE)

Limiting the type of column return can help reduce loading time fairly substantially.

**Comment by broakenmedia** [comment]
1.8.3 now available! See readme
