### ISSUE TITLE
 Function of Searching

### ISSUE THREAD

**Issue by DenisWu** [broakenmedia/MultiContactPicker#2]
I admire your good job! 
Just give you an advice after I used it.
My phone have  hundreds of contacts, and it is a little hard for me to find the target.
So can you add the funciton of Searching?

**Comment by broakenmedia** [comment]
Thank you! Are you not able to use the alphabetical fast scroll? By dragging scroll bar directly to the intended contact

On 29 Aug 2017, at 10:54 am, DenisWu <notifications@github.com<mailto:notifications@github.com>> wrote:


I admire your good job!
Just give you an advice after I used it.
My phone have hundreds of contacts, and it is a little hard for me to find the target.
So can you add the funciton of Searching?

**Comment by DenisWu** [comment]
Yes, I can use it. I think that can be more flexible, because I always use Searching on my phone.

**Comment by broakenmedia** [comment]
searched added!

**Comment by DenisWu** [comment]
Thank you for that! I upgrate the the code.
In the last version, it displays all the contacts in less then 500ms.
But this version takes serveral seconds. Do you find it?
Besides, In the first search result, I choose a contact. And continue to the second search, I choose another contact. Finally  the result does not contain the first contact.

**Comment by broakenmedia** [comment]
Are you pulling down the source code or using through gradle?
