### ISSUE TITLE
Not picking both contacts by adding key "Mobile" and "Home". Picking only first contact number.

### ISSUE THREAD

**Issue by 6neeru** [broakenmedia/MultiContactPicker#24]

**Comment by broakenmedia** [comment]
Hi, the contact result object has a list of phone numbers for each contact which should be every number on "file"

    results.get(0).getPhoneNumbers().get(X)

They aren't labeled which is which however, is that what you're asking for?

**Comment by 6neeru** [comment]
Thanks for reply.


Issue is I am saving 2 phone numbers with same name i.e "Aa"(Screenshot 1)
but library is fetching only one

(Screenshot 2)  .
Please refer screenshots

**Comment by broakenmedia** [comment]
I cannot see any screenshots?

**Comment by 6neeru** [comment]
Hi,

i had attached in same mail.

**Comment by broakenmedia** [comment]
I'm afraid i do not have them. Please either upload them here or to somewhere like imgur

**Comment by 6neeru** [comment]
![screenshot_1 1](https://user-images.githubusercontent.com/42429283/45819045-f9005b80-bd00-11e8-98a0-7045ce3897f0.png)
![screenshot_2](https://user-images.githubusercontent.com/42429283/45819051-01589680-bd01-11e8-8acb-1f24ee499800.png)



Please check, and how i can remove my contact number from my list

**Comment by broakenmedia** [comment]
OK great. The picker simply displays the primary phone number. If you select your Aa contact, in the ContactResult object you'll be able to get both the Mobile and Home number using what i mentioned before.

    results.get(0).getPhoneNumbers().get(0) - mobile
    results.get(0).getPhoneNumbers().get(1) - home

I may look into adding keys for these numbers in the next release so you're able to identify which is which.
