### ISSUE TITLE
Get selected contacts into listview

### ISSUE THREAD

**Issue by zubairhashim93** [broakenmedia/MultiContactPicker#25]
How can i populate the "results" selected contacts into listview,  i have added the listview with the same activity as **open picker** button

**Comment by broakenmedia** [comment]
Can you re-phrase? I'm not too sure what you mean

**Comment by zubairhashim93** [comment]
Thanks for the response.
I want to view the selected contacts into list view.
When I selected contacts and click on finish, selected contacts should view in a listview.
I added a listview in open picker button activity.
I tried with arrayadapter but it's not working

**Comment by zubairhashim93** [comment]
As I can see the selected contacts is passed into "results" array list but it's not giving any review of selected contacts.
All I want is selected contacts in a listview, so that user can review the selected contacts before doing any action with selected contacts.
Please help me to fix this issue

**Comment by broakenmedia** [comment]
Hi,

I'm afraid that sounds more like an implementation issue in your app rather than an issue with the library. You may want to ask over on stackoverflow.

You can take the List<ContactResult> results and use this in your own adapter however you like.
