### ISSUE TITLE
how to set a limit for selecting contacts from list.

### ISSUE THREAD

**Issue by adarshvijayanp** [broakenmedia/MultiContactPicker#28]
I like to set maximum number of contacts can be selected from the given contact list , example 100.
How can i achieve this?

**Comment by broakenmedia** [comment]
Can you give me a use case for this?

**Comment by adarshvijayanp** [comment]
There is a certain amount of price money for each contact upload, so i need to prevent user from adding more than certain number of contacts , eg: 100.
But there is a  **select all** option most of the user will try to select all contact from their phone book.

**Comment by adarshvijayanp** [comment]
There is a certain amount of price money for each contact upload, so i need to prevent user from adding more than certain number of contacts , eg: 100.
But there is a select all option most of the user will try to select all contact from their phone book.

**Comment by broakenmedia** [comment]
I would recommend using the ‘CHOICE_MODE_SINGLE’ then handling the logic for limiting the number of selections in your own app.

On 5 Oct 2018, at 11:03 am, Adarsh Vijayan P <notifications@github.com<mailto:notifications@github.com>> wrote:


There is a certain amount of price money for each contact upload, so i need to prevent user from adding more than certain number of contacts , eg: 100.
But there is a select all option most of the user will try to select all contact from their phone book.

**Comment by adarshvijayanp** [comment]
Ok thanks.
