### ISSUE TITLE
It's not possible to override transition when open and finish MultiContactPickerActivity

### ISSUE THREAD

**Issue by NeoSyder** [broakenmedia/MultiContactPicker#29]
Usually I use this method `overridePendingTransition(R.anim.activity_in, R.anim.activity_out);` after `startActivity()` or `startActivityForResult()`, and `overridePendingTransition(R.anim.activity_back_in, R.anim.activity_back_out);` after `finish()`

**Comment by broakenmedia** [comment]
This will be available in the next release. Likely coming today.

**Comment by broakenmedia** [comment]
Available in 1.8.5
