### ISSUE TITLE
Contacts not showing on Huawey P10 lite

### ISSUE THREAD

**Issue by GangemiLorenzo** [broakenmedia/MultiContactPicker#3]
MultiContactPicker works really fine on each device I've tried, but on the Huawei P10 lite, with android N it doesn't works.

The Dialog shows up but **no contact is showing**.

Here's my code:

`    new MultiContactPicker.Builder(getActivity()) 
                        .hideScrollbar(false)
                        .showTrack(false)
                        .handleColor(ContextCompat.getColor(getActivity(), R.color.colorAccent))
                        .bubbleColor(ContextCompat.getColor(getActivity(), R.color.colorPrimary))
                        .textColor(Color.WHITE)
                        .showPickerForResult(CONTACT_PICKER_CLIENTI);`

**Comment by GangemiLorenzo** [comment]
Just figure out I wasn't asking runtime permissions. Sorry for the Issue.

**Comment by broakenmedia** [comment]
Have you requested the contacts runtime permissions?

On 29 Aug 2017, at 8:30 pm, Lorenzo Gangemi <notifications@github.com<mailto:notifications@github.com>> wrote:


MultiContactPicker works really fine on each device I've tried, but on the Huawei P10 lite, with android N it doesn't works.

The Dialog shows up but no contact is showing.

Here's my code:

new MultiContactPicker.Builder(getActivity()) .hideScrollbar(false) .showTrack(false) .handleColor(ContextCompat.getColor(getActivity(), R.color.colorAccent)) .bubbleColor(ContextCompat.getColor(getActivity(), R.color.colorPrimary)) .textColor(Color.WHITE) .showPickerForResult(CONTACT_PICKER_CLIENTI);

**Comment by GangemiLorenzo** [comment]
Permissions are the problem, thanks!

**Comment by GangemiLorenzo** [comment]
I reopened the issue becouse the permission were a problem but there is something else too.

Contacts are not showing up and this is the logcat:

`
08-29 21:43:27.549 16505-16505/lorenzogangemideveloper.insurancehelper W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.compareToIgnoreCase(java.lang.String)' on a null object reference
08-29 21:43:27.550 16505-16505/lorenzogangemideveloper.insurancehelper W/System.err:     at com.wafflecopter.multicontactpicker.MultiContactPickerActivity$4.compare(MultiContactPickerActivity.java:114)
08-29 21:43:27.550 16505-16505/lorenzogangemideveloper.insurancehelper W/System.err:     at com.wafflecopter.multicontactpicker.MultiContactPickerActivity$4.compare(MultiContactPickerActivity.java:111)
08-29 21:43:27.550 16505-16505/lorenzogangemideveloper.insurancehelper W/System.err:     at java.util.TimSort.binarySort(TimSort.java:292)
08-29 21:43:27.550 16505-16505/lorenzogangemideveloper.insurancehelper W/System.err:     at java.util.TimSort.sort(TimSort.java:235)
08-29 21:43:27.550 16505-16505/lorenzogangemideveloper.insurancehelper W/System.err:     at java.util.Arrays.sort(Arrays.java:1523)
08-29 21:43:27.550 16505-16505/lorenzogangemideveloper.insurancehelper W/System.err:     at java.util.Collections.sort(Collections.java:238)
08-29 21:43:27.550 16505-16505/lorenzogangemideveloper.insurancehelper W/System.err:     at io.reactivex.internal.functions.Functions$ListSorter.apply(Functions.java:633)
08-29 21:43:27.550 16505-16505/lorenzogangemideveloper.insurancehelper W/System.err:     at io.reactivex.internal.functions.Functions$ListSorter.apply(Functions.java:624)
08-29 21:43:27.550 16505-16505/lorenzogangemideveloper.insurancehelper W/System.err:     at io.reactivex.internal.operators.single.SingleMap$1.onSuccess(SingleMap.java:43)
08-29 21:43:27.550 16505-16505/lorenzogangemideveloper.insurancehelper W/System.err:     at io.reactivex.internal.operators.observable.ObservableToListSingle$ToListObserver.onComplete(ObservableToListSingle.java:113)
08-29 21:43:27.550 16505-16505/lorenzogangemideveloper.insurancehelper W/System.err:     at io.reactivex.internal.operators.observable.ObservableCreate$CreateEmitter.onComplete(ObservableCreate.java:91)
08-29 21:43:27.550 16505-16505/lorenzogangemideveloper.insurancehelper W/System.err:     at com.wafflecopter.multicontactpicker.RxContacts.RxContacts.fetch(RxContacts.java:100)
08-29 21:43:27.550 16505-16505/lorenzogangemideveloper.insurancehelper W/System.err:     at com.wafflecopter.multicontactpicker.RxContacts.RxContacts.access$100(RxContacts.java:31)
08-29 21:43:27.551 16505-16505/lorenzogangemideveloper.insurancehelper W/System.err:     at com.wafflecopter.multicontactpicker.RxContacts.RxContacts$1.subscribe(RxContacts.java:49)
08-29 21:43:27.551 16505-16505/lorenzogangemideveloper.insurancehelper W/System.err:     at io.reactivex.internal.operators.observable.ObservableCreate.subscribeActual(ObservableCreate.java:40)
08-29 21:43:27.551 16505-16505/lorenzogangemideveloper.insurancehelper W/System.err:     at io.reactivex.Observable.subscribe(Observable.java:10179)
08-29 21:43:27.551 16505-16505/lorenzogangemideveloper.insurancehelper W/System.err:     at io.reactivex.internal.operators.observable.ObservableToListSingle.subscribeActual(ObservableToListSingle.java:58)
08-29 21:43:27.551 16505-16505/lorenzogangemideveloper.insurancehelper W/System.err:     at io.reactivex.Single.subscribe(Single.java:2558)
08-29 21:43:27.551 16505-16505/lorenzogangemideveloper.insurancehelper W/System.err:     at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:33)
08-29 21:43:27.551 16505-16505/lorenzogangemideveloper.insurancehelper W/System.err:     at io.reactivex.Single.subscribe(Single.java:2558)
08-29 21:43:27.551 16505-16505/lorenzogangemideveloper.insurancehelper W/System.err:     at io.reactivex.internal.operators.single.SingleObserveOn.subscribeActual(SingleObserveOn.java:35)
08-29 21:43:27.551 16505-16505/lorenzogangemideveloper.insurancehelper W/System.err:     at io.reactivex.Single.subscribe(Single.java:2558)
08-29 21:43:27.551 16505-16505/lorenzogangemideveloper.insurancehelper W/System.err:     at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
08-29 21:43:27.551 16505-16505/lorenzogangemideveloper.insurancehelper W/System.err:     at io.reactivex.Scheduler$1.run(Scheduler.java:134)
08-29 21:43:27.551 16505-16505/lorenzogangemideveloper.insurancehelper W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:59)
08-29 21:43:27.551 16505-16505/lorenzogangemideveloper.insurancehelper W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:51)
08-29 21:43:27.551 16505-16505/lorenzogangemideveloper.insurancehelper W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
08-29 21:43:27.551 16505-16505/lorenzogangemideveloper.insurancehelper W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
08-29 21:43:27.551 16505-16505/lorenzogangemideveloper.insurancehelper W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
08-29 21:43:27.551 16505-16505/lorenzogangemideveloper.insurancehelper W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
08-29 21:43:27.551 16505-16505/lorenzogangemideveloper.insurancehelper W/System.err:     at java.lang.Thread.run(Thread.java:776)`

**Comment by broakenmedia** [comment]
What are you calling 'compareToIgnoreCase' on? 

Name or number or something?

**Comment by GangemiLorenzo** [comment]
Sorry, i can't figure out what is 'compareTolgnoreCase'.

The only code i wrote is the one i wrote in first comment.

**Comment by broakenmedia** [comment]
Ah ok sorry, it's because that one of your contacts has a null displayName, will add a check for that and replace the name with the phoneNumber/email

**Comment by GangemiLorenzo** [comment]
Good, thanks! 
For now I'll look for the "no name" contact.

**Comment by broakenmedia** [comment]
Great, can you let me know if you figure out which contact is causing it? I cannot seem to replicate it so far, even if i just create an empty contact for example

**Comment by GangemiLorenzo** [comment]
The Contact was not only one, there were like 10 or more contacts which had no data. 
No Contact name, no phoneNumber, no Email. 
The Huaway P10 was displaying them at the end of his contact app with a label like "(No Name)".
After deleting them all works fine.
