### ISSUE TITLE
It's not possible de block screenOrientation with manifest

### ISSUE THREAD

**Issue by NeoSyder** [broakenmedia/MultiContactPicker#30]
How to use your MultiContactPickerActivity in manifest to add option like `android:screenOrientation`

**Comment by broakenmedia** [comment]
Simply add

    <activity android:name="com.wafflecopter.multicontactpicker.MultiContactPickerActivity"
                  android:label="@string/picker_title"
            android:screenOrientation="portrait">
        </activity>

to your applications manifest to override that of MCP
