### ISSUE TITLE
How to notify RecyclerView for new set of contacts selected?

### ISSUE THREAD

**Issue by HmdH95** [broakenmedia/MultiContactPicker#36]
I'm showing the selected contacts in a `Recyclerview`. But when I select another set of contacts, it adds them to the previous ones. how can i remove the previously selected contacts when I select new ones?

**Comment by lolsheeplol** [comment]
It sounds like you're just adding items to the `List<ContactResult>` that the recyclervie adapter is using.  You'll need to find a way to clear that list before you add new items if you want it to replace the recyclerview contents (e.g. `adapter.clear()` then `adapter.notifyDataSetChanaged()`).  You will probably have to write that clear method yourself. 

If you want an example gist for something like a `BaseRecyclerAdapter` that helps with these kinds of operations, let me know.

**Comment by broakenmedia** [comment]
This is an implementation detail for your own app not an issue with the lib as far as i can tell! Simply maintain your own list and clear and fill as necessary. Thank you @lolsheeplol !
