### ISSUE TITLE
Feature Request: Addresses

### ISSUE THREAD

**Issue by mandrachek** [broakenmedia/MultiContactPicker#4]
If would be great if the ContactResult also contained address information in addition to phone numbers and email addresses.

**Comment by broakenmedia** [comment]
I see you've been adding to this on a fork, did you want to submit a pull request so i can pull in the changes?

**Comment by mandrachek** [comment]
@broakenmedia 
I'm happy to submit the pull request for you, but it is API breaking and poorly documented.

My specific use-cases (importing contacts from the system into my app) includes multiple email addresses, phone numbers, and mailing addresses, and including labels (Home, Work, Fax, etc.) for each.
