### ISSUE TITLE
Crash 

### ISSUE THREAD

**Issue by shimiuh** [broakenmedia/MultiContactPicker#9]
Just add a null check please

Fatal Exception: java.lang.NullPointerException
Attempt to invoke interface method 'boolean android.database.Cursor.moveToFirst()' on a null object reference
keyboard_arrow_up
arrow_right
com.onegravity.contactpicker.core.ContactPickerActivity.readContacts (ContactPickerActivity.java:603)
com.onegravity.contactpicker.core.ContactPickerActivity.onLoadFinished (ContactPickerActivity.java:551)
com.onegravity.contactpicker.core.ContactPickerActivity.onLoadFinished (ContactPickerActivity.java:69)
android.support.v4.app.LoaderManagerImpl$LoaderInfo.callOnLoadFinished (LoaderManager.java:476)
android.support.v4.app.LoaderManagerImpl$LoaderInfo.onLoadComplete (LoaderManager.java:444)
android.support.v4.content.Loader.deliverResult (Loader.java:126)
android.support.v4.content.CursorLoader.deliverResult (CursorLoader.java:105)
android.support.v4.content.CursorLoader.deliverResult (CursorLoader.java:37)
android.support.v4.content.AsyncTaskLoader.dispatchOnLoadComplete (AsyncTaskLoader.java:255)
android.support.v4.content.AsyncTaskLoader$LoadTask.onPostExecute (AsyncTaskLoader.java:80)
android.support.v4.content.ModernAsyncTask.finish (ModernAsyncTask.java:487)
android.support.v4.content.ModernAsyncTask$InternalHandler.handleMessage (ModernAsyncTask.java:504)
android.os.Handler.dispatchMessage (Handler.java:111)
android.os.Looper.loop (Looper.java:210)
android.app.ActivityThread.main (ActivityThread.java:5833)
java.lang.reflect.Method.invoke (Method.java)
java.lang.reflect.Method.invoke (Method.java:372)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1113)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:879)

**Comment by broakenmedia** [comment]
I'm not sure what you're referring to? I don't have an activity called ContactPickerActivity nor is it 600+ lines long?
